# Generated by Django 3.2.3 on 2021-05-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='Sem categoria', max_length=255),
            preserve_default=False,
        ),
    ]
